services:
  db:
    image: postgres:latest
    ports:
      -"5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  pgadmin:
    image: dpage/pgadmin4
    container_name: hostpital-management-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db